sudo: required
services:
 - docker
before_install:
 # - docker pull surendrajat/twrp-builder:latest
before_script:
 # - cd $HOME && mkdir twrp
 # - wget -q https://github.com/TwrpBuilder/twrp-sources/releases/download/omni_twrp-5.1.1-cleaned/omni_twrp-5.1.1_cleaned.tar.xz -O $HOME/twrp.tar.xz
 # - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
 - cd $HOME/
 - git clone https://github.com/M1Dr05/IsTheApp
 - cd IsTheApp
 - sudo apt-get install gradle
 - gradle build
 
